language: objective-c

# the target workspace
xcode_workspace: motion-detect.xcworkspace # path to your xcodeproj folder
# the target test scheme
xcode_scheme: motiondetectTests

#before_install:
#     - brew update
#     - brew install xctool

#script: xctool -project motion-detect.xcworkspace \
# -scheme motiondetectTests test


# it seems for a long command, we can split it arbitrary?
# but escape \ at command end and a dash at starting for new command is necessary

# script before install
before_install:
  - echo 'ready   go gogogo a long long sentence'
  - echo 'ready 2'
# script for install
install:
  echo 'installing'

# script after success
after_success:
  echo 'done'
#script after fail
after_failure:
  echo 'fail'

# script after done
after_script:
  echo 'after'

